// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK6t6xfw1Pzjmu5yCK7BTQPRwZhDQ3pSs',
    appId: '1:622156377073:web:f0aa2828a77a3a083a7250',
    messagingSenderId: '622156377073',
    projectId: 'fireexampleprojects',
    authDomain: 'fireexampleprojects.firebaseapp.com',
    storageBucket: 'fireexampleprojects.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0UiIU7uAXryXOZuzHe0-2MB3HWCbAAOk',
    appId: '1:622156377073:android:e77b5c1713ad8e223a7250',
    messagingSenderId: '622156377073',
    projectId: 'fireexampleprojects',
    storageBucket: 'fireexampleprojects.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyKp5DwpLeFXZhIzJmRox7vcieZ5uvAtE',
    appId: '1:622156377073:ios:3bbb659822cc4af83a7250',
    messagingSenderId: '622156377073',
    projectId: 'fireexampleprojects',
    storageBucket: 'fireexampleprojects.appspot.com',
    iosClientId: '622156377073-asme7ojofb0rep2vfbe4ek9he2ku5it4.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyKp5DwpLeFXZhIzJmRox7vcieZ5uvAtE',
    appId: '1:622156377073:ios:3bbb659822cc4af83a7250',
    messagingSenderId: '622156377073',
    projectId: 'fireexampleprojects',
    storageBucket: 'fireexampleprojects.appspot.com',
    iosClientId: '622156377073-asme7ojofb0rep2vfbe4ek9he2ku5it4.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireExample',
  );
}
